name: Release

on:
  push:
    branches: [ master, development ]
    paths:
      - 'src/**'
      - '.github/workflows/release.yml'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: use-actions
      uses: gittools/actions@v0.9.3

    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Cache Nuget
      uses: actions/cache@v1
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Build
      working-directory: src
      run: |
        dotnet restore --disable-parallel --locked-mode
        dotnet build --disable-parallel --configuration Release

    - name: Use GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.3

    - name: set preRelease
      uses: allenevans/set-env@v1.0.0
      with:
        isPreRelease: 'true'

    - name: check preRelease
      if: ${{ steps.gitversion.outputs.preReleaseLabel  == ''  }}
      uses: allenevans/set-env@v1.0.0
      with:
        isPreRelease: 'false'

    - name: Create release
      uses: gittools/actions/gitreleasemanager/create@v0.9.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        owner: ${{ github.repository_owner }}
        repository: 'qlik-connectapi'
        isPreRelease: ${{ env.isPreRelease }}
        milestone: ${{ steps.gitversion.outputs.semVer }}
        name: ${{ steps.gitversion.outputs.semVer }}
        assets: |
          src\bin\Release\qlik-connectapi.${{ steps.gitversion.outputs.nuGetVersion  }}.nupkg